baseurl = "http://pepsfeeder.com/"
title = "pepsfeeder"
languageCode = "en"
# Disqus shortname
disqusShortname = "pepsfeeder-com-1"
# google analytics tracking id
googleAnalytics = "UA-151759850-1"

googlefonts = "https://fonts.googleapis.com/css?family=Merriweather|Fira+Mono|Droid+Sans|Fira+Code"

[markup.goldmark.renderer]
unsafe= true

# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2020 pepsfeeder"

[params]
  # whether to use CDN or local file for fontawesome
  #useCDN = false
  # whether to include external sharing scripts and icons for twitter, facebook and co.
  #showShareIcons = false
  # Date format
  #dateFormat = "January 2, 2006"

# This is displayer in About page.
[params.author]
  name = "Chris Mano"
  # Gravatar or Abatar image
  gravatar = "Gravatar email or MD5 Hash"
  #avatar = "/path/to/avatar"

  twitter = "pepsfeeder"
  facebook = "pepsfeeder"
  googleplus = "Googleplus username"
  instagram = "Instagram username"
  tumblr = "Tumblr username"
  flickr = "Flickr username"
  reddit = "Reddit username"
  linkedin = "Linkedin username"
  slideshare = "Slideshare username"
  github = "Github username"
  gitlab = "Gitlab username"
  bitbucket = "Bitbucket username"
  stackoverflow = "Stackoverflow username"
  jsfiddle = "Jsfiddle username"
  codepen = "Codepen username"
  deviantart = "Deviantart username"
  behance = "Behance username"
  dribbble = "Dribbble username"
  wordpress = "Wordpress username"
  medium = "Medium username"
  foursquare = "Foursquare username"
  xing = "Xing username"
  quora = "Quora username"
  youtube = "Youtube username"
  vimeo = "Vimeo username"
  whatsapp = "Whatsapp username"
  skype = "Skype username"
  snapchat = "Snapchat username"
  pinterest = "pepsfeeder"
  telegram = "Telegram username"
  vine = "Vine username"
  email = "support@pepsfeeder.com"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# Header Menu
[[menu.main]]
  name = "Wellness"
  identifier = "wellness"
  url = "/"
  weight = 1
[[menu.main]]
  name = "News"
  identifier = "news"
  url = "/"
  weight = 2
[[menu.main]]
  name = "Lifestyle"
  identifier = "lifestyle"
  url = "/"
  weight = 3
[[menu.main]]
  name = "Entertainment"
  identifier = "entertainment"
  url = "/"
  weight = 4
[[menu.main]]
  name = "Gen Z"
  identifier = "genz"
  url = "/"
  weight = 5

# Footer Menu
[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"
[[menu.footer]]
  name = "Authors"
  weight = 2
  identifier = "authors"
  url = "/authors/"
[[menu.footer]]
  name = "Contacts"
  weight = 3
  identifier = "contacts"
  url = "/contacts/"
[[menu.footer]]
  name = "DMCA"
  weight = 4
  identifier = "dcma"
  url = "/dcma/"
[[menu.footer]]
  name = "Privacy Policy"
  weight = 5
  identifier = "privacy"
  url = "/privacy/"
[[menu.footer]]
  name = "Terms of Use"
  weight = 6
  identifier = "terms"
  url = "/terms/"
[[menu.footer]]
  name = "Staff"
  weight = 7
  identifier = "staff"
  url = "/staff/"
